# Generated by Django 4.1.5 on 2023-01-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='upated_at',
            new_name='updated_at',
        ),
    ]
